/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarchesPrivesRouteImport } from './routes/marches-prives'
import { Route as MarchesPublicsIndexRouteImport } from './routes/marches-publics.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesPrivesRoute = MarchesPrivesRouteImport.update({
  id: '/marches-prives',
  path: '/marches-prives',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesPublicsIndexRoute = MarchesPublicsIndexRouteImport.update({
  id: '/marches-publics/',
  path: '/marches-publics/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/marches-prives': typeof MarchesPrivesRoute
  '/marches-publics/': typeof MarchesPublicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/marches-prives': typeof MarchesPrivesRoute
  '/marches-publics': typeof MarchesPublicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/marches-prives': typeof MarchesPrivesRoute
  '/marches-publics/': typeof MarchesPublicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/marches-prives'
    | '/marches-publics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/marches-prives'
    | '/marches-publics'
  id:
    | '__root__'
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/marches-prives'
    | '/marches-publics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurationRoute: typeof ConfigurationRoute
  DashboardRoute: typeof DashboardRoute
  MarchesPrivesRoute: typeof MarchesPrivesRoute
  MarchesPublicsIndexRoute: typeof MarchesPublicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches-prives': {
      id: '/marches-prives'
      path: '/marches-prives'
      fullPath: '/marches-prives'
      preLoaderRoute: typeof MarchesPrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches-publics/': {
      id: '/marches-publics/'
      path: '/marches-publics'
      fullPath: '/marches-publics/'
      preLoaderRoute: typeof MarchesPublicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurationRoute: ConfigurationRoute,
  DashboardRoute: DashboardRoute,
  MarchesPrivesRoute: MarchesPrivesRoute,
  MarchesPublicsIndexRoute: MarchesPublicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
