/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as FacturationRouteImport } from './routes/facturation'
import { Route as BrigadesIndexRouteImport } from './routes/brigades.index'
import { Route as BrigadesIdRouteImport } from './routes/brigades.$id'
import { Route as MarchesPrivesIndexRouteImport } from './routes/marches-prives.index'
import { Route as MarchesPrivesRefRouteImport } from './routes/marches-prives.$ref'
import { Route as MarchesPublicsIndexRouteImport } from './routes/marches-publics.index'
import { Route as MarchesPublicsRefRouteImport } from './routes/marches-publics.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturationRoute = FacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigadesIndexRoute = BrigadesIndexRouteImport.update({
  id: '/brigades/',
  path: '/brigades/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigadesIdRoute = BrigadesIdRouteImport.update({
  id: '/brigades/$id',
  path: '/brigades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesPrivesIndexRoute = MarchesPrivesIndexRouteImport.update({
  id: '/marches-prives/',
  path: '/marches-prives/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesPrivesRefRoute = MarchesPrivesRefRouteImport.update({
  id: '/marches-prives/$ref',
  path: '/marches-prives/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesPublicsIndexRoute = MarchesPublicsIndexRouteImport.update({
  id: '/marches-publics/',
  path: '/marches-publics/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesPublicsRefRoute = MarchesPublicsRefRouteImport.update({
  id: '/marches-publics/$ref',
  path: '/marches-publics/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/dossiers': typeof DossiersRoute
  '/facturation': typeof FacturationRoute
  '/brigades/$id': typeof BrigadesIdRoute
  '/marches-prives/$ref': typeof MarchesPrivesRefRoute
  '/marches-publics/$ref': typeof MarchesPublicsRefRoute
  '/brigades/': typeof BrigadesIndexRoute
  '/marches-prives/': typeof MarchesPrivesIndexRoute
  '/marches-publics/': typeof MarchesPublicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/dossiers': typeof DossiersRoute
  '/facturation': typeof FacturationRoute
  '/brigades/$id': typeof BrigadesIdRoute
  '/marches-prives/$ref': typeof MarchesPrivesRefRoute
  '/marches-publics/$ref': typeof MarchesPublicsRefRoute
  '/brigades': typeof BrigadesIndexRoute
  '/marches-prives': typeof MarchesPrivesIndexRoute
  '/marches-publics': typeof MarchesPublicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/dashboard': typeof DashboardRoute
  '/dossiers': typeof DossiersRoute
  '/facturation': typeof FacturationRoute
  '/brigades/$id': typeof BrigadesIdRoute
  '/marches-prives/$ref': typeof MarchesPrivesRefRoute
  '/marches-publics/$ref': typeof MarchesPublicsRefRoute
  '/brigades/': typeof BrigadesIndexRoute
  '/marches-prives/': typeof MarchesPrivesIndexRoute
  '/marches-publics/': typeof MarchesPublicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/dossiers'
    | '/facturation'
    | '/brigades/$id'
    | '/marches-prives/$ref'
    | '/marches-publics/$ref'
    | '/brigades/'
    | '/marches-prives/'
    | '/marches-publics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/dossiers'
    | '/facturation'
    | '/brigades/$id'
    | '/marches-prives/$ref'
    | '/marches-publics/$ref'
    | '/brigades'
    | '/marches-prives'
    | '/marches-publics'
  id:
    | '__root__'
    | '/'
    | '/configuration'
    | '/dashboard'
    | '/dossiers'
    | '/facturation'
    | '/brigades/$id'
    | '/marches-prives/$ref'
    | '/marches-publics/$ref'
    | '/brigades/'
    | '/marches-prives/'
    | '/marches-publics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurationRoute: typeof ConfigurationRoute
  DashboardRoute: typeof DashboardRoute
  DossiersRoute: typeof DossiersRoute
  FacturationRoute: typeof FacturationRoute
  BrigadesIdRoute: typeof BrigadesIdRoute
  MarchesPrivesRefRoute: typeof MarchesPrivesRefRoute
  MarchesPublicsRefRoute: typeof MarchesPublicsRefRoute
  BrigadesIndexRoute: typeof BrigadesIndexRoute
  MarchesPrivesIndexRoute: typeof MarchesPrivesIndexRoute
  MarchesPublicsIndexRoute: typeof MarchesPublicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturation': {
      id: '/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof FacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigades/': {
      id: '/brigades/'
      path: '/brigades'
      fullPath: '/brigades/'
      preLoaderRoute: typeof BrigadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigades/$id': {
      id: '/brigades/$id'
      path: '/brigades/$id'
      fullPath: '/brigades/$id'
      preLoaderRoute: typeof BrigadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches-prives/': {
      id: '/marches-prives/'
      path: '/marches-prives'
      fullPath: '/marches-prives/'
      preLoaderRoute: typeof MarchesPrivesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches-prives/$ref': {
      id: '/marches-prives/$ref'
      path: '/marches-prives/$ref'
      fullPath: '/marches-prives/$ref'
      preLoaderRoute: typeof MarchesPrivesRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches-publics/': {
      id: '/marches-publics/'
      path: '/marches-publics'
      fullPath: '/marches-publics/'
      preLoaderRoute: typeof MarchesPublicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches-publics/$ref': {
      id: '/marches-publics/$ref'
      path: '/marches-publics/$ref'
      fullPath: '/marches-publics/$ref'
      preLoaderRoute: typeof MarchesPublicsRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurationRoute: ConfigurationRoute,
  DashboardRoute: DashboardRoute,
  DossiersRoute: DossiersRoute,
  FacturationRoute: FacturationRoute,
  BrigadesIdRoute: BrigadesIdRoute,
  MarchesPrivesRefRoute: MarchesPrivesRefRoute,
  MarchesPublicsRefRoute: MarchesPublicsRefRoute,
  BrigadesIndexRoute: BrigadesIndexRoute,
  MarchesPrivesIndexRoute: MarchesPrivesIndexRoute,
  MarchesPublicsIndexRoute: MarchesPublicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
